// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteNumericAttributeValueBitmapStmt, err = db.PrepareContext(ctx, deleteNumericAttributeValueBitmap); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNumericAttributeValueBitmap: %w", err)
	}
	if q.deletePayloadForEntityKeyStmt, err = db.PrepareContext(ctx, deletePayloadForEntityKey); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePayloadForEntityKey: %w", err)
	}
	if q.deleteStringAttributeValueBitmapStmt, err = db.PrepareContext(ctx, deleteStringAttributeValueBitmap); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteStringAttributeValueBitmap: %w", err)
	}
	if q.evaluateAllStmt, err = db.PrepareContext(ctx, evaluateAll); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateAll: %w", err)
	}
	if q.evaluateNumericAttributeValueEqualStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueEqual); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueEqual: %w", err)
	}
	if q.evaluateNumericAttributeValueGreaterOrEqualThanStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueGreaterOrEqualThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueGreaterOrEqualThan: %w", err)
	}
	if q.evaluateNumericAttributeValueGreaterThanStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueGreaterThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueGreaterThan: %w", err)
	}
	if q.evaluateNumericAttributeValueInclusionStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueInclusion); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueInclusion: %w", err)
	}
	if q.evaluateNumericAttributeValueLessOrEqualThanStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueLessOrEqualThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueLessOrEqualThan: %w", err)
	}
	if q.evaluateNumericAttributeValueLowerThanStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueLowerThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueLowerThan: %w", err)
	}
	if q.evaluateNumericAttributeValueNotEqualStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueNotEqual); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueNotEqual: %w", err)
	}
	if q.evaluateNumericAttributeValueNotInclusionStmt, err = db.PrepareContext(ctx, evaluateNumericAttributeValueNotInclusion); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateNumericAttributeValueNotInclusion: %w", err)
	}
	if q.evaluateStringAttributeValueEqualStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueEqual); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueEqual: %w", err)
	}
	if q.evaluateStringAttributeValueGlobStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueGlob); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueGlob: %w", err)
	}
	if q.evaluateStringAttributeValueGreaterOrEqualThanStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueGreaterOrEqualThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueGreaterOrEqualThan: %w", err)
	}
	if q.evaluateStringAttributeValueGreaterThanStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueGreaterThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueGreaterThan: %w", err)
	}
	if q.evaluateStringAttributeValueInclusionStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueInclusion); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueInclusion: %w", err)
	}
	if q.evaluateStringAttributeValueLessOrEqualThanStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueLessOrEqualThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueLessOrEqualThan: %w", err)
	}
	if q.evaluateStringAttributeValueLowerThanStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueLowerThan); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueLowerThan: %w", err)
	}
	if q.evaluateStringAttributeValueNotEqualStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueNotEqual); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueNotEqual: %w", err)
	}
	if q.evaluateStringAttributeValueNotGlobStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueNotGlob); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueNotGlob: %w", err)
	}
	if q.evaluateStringAttributeValueNotInclusionStmt, err = db.PrepareContext(ctx, evaluateStringAttributeValueNotInclusion); err != nil {
		return nil, fmt.Errorf("error preparing query EvaluateStringAttributeValueNotInclusion: %w", err)
	}
	if q.getLastBlockStmt, err = db.PrepareContext(ctx, getLastBlock); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastBlock: %w", err)
	}
	if q.getNumberOfEntitiesStmt, err = db.PrepareContext(ctx, getNumberOfEntities); err != nil {
		return nil, fmt.Errorf("error preparing query GetNumberOfEntities: %w", err)
	}
	if q.getNumericAttributeValueBitmapStmt, err = db.PrepareContext(ctx, getNumericAttributeValueBitmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetNumericAttributeValueBitmap: %w", err)
	}
	if q.getPayloadForEntityKeyStmt, err = db.PrepareContext(ctx, getPayloadForEntityKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetPayloadForEntityKey: %w", err)
	}
	if q.getStringAttributeValueBitmapStmt, err = db.PrepareContext(ctx, getStringAttributeValueBitmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetStringAttributeValueBitmap: %w", err)
	}
	if q.retrievePayloadsStmt, err = db.PrepareContext(ctx, retrievePayloads); err != nil {
		return nil, fmt.Errorf("error preparing query RetrievePayloads: %w", err)
	}
	if q.upsertLastBlockStmt, err = db.PrepareContext(ctx, upsertLastBlock); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertLastBlock: %w", err)
	}
	if q.upsertNumericAttributeValueBitmapStmt, err = db.PrepareContext(ctx, upsertNumericAttributeValueBitmap); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertNumericAttributeValueBitmap: %w", err)
	}
	if q.upsertPayloadStmt, err = db.PrepareContext(ctx, upsertPayload); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertPayload: %w", err)
	}
	if q.upsertStringAttributeValueBitmapStmt, err = db.PrepareContext(ctx, upsertStringAttributeValueBitmap); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertStringAttributeValueBitmap: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteNumericAttributeValueBitmapStmt != nil {
		if cerr := q.deleteNumericAttributeValueBitmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNumericAttributeValueBitmapStmt: %w", cerr)
		}
	}
	if q.deletePayloadForEntityKeyStmt != nil {
		if cerr := q.deletePayloadForEntityKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePayloadForEntityKeyStmt: %w", cerr)
		}
	}
	if q.deleteStringAttributeValueBitmapStmt != nil {
		if cerr := q.deleteStringAttributeValueBitmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteStringAttributeValueBitmapStmt: %w", cerr)
		}
	}
	if q.evaluateAllStmt != nil {
		if cerr := q.evaluateAllStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateAllStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueEqualStmt != nil {
		if cerr := q.evaluateNumericAttributeValueEqualStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueEqualStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueGreaterOrEqualThanStmt != nil {
		if cerr := q.evaluateNumericAttributeValueGreaterOrEqualThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueGreaterOrEqualThanStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueGreaterThanStmt != nil {
		if cerr := q.evaluateNumericAttributeValueGreaterThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueGreaterThanStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueInclusionStmt != nil {
		if cerr := q.evaluateNumericAttributeValueInclusionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueInclusionStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueLessOrEqualThanStmt != nil {
		if cerr := q.evaluateNumericAttributeValueLessOrEqualThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueLessOrEqualThanStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueLowerThanStmt != nil {
		if cerr := q.evaluateNumericAttributeValueLowerThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueLowerThanStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueNotEqualStmt != nil {
		if cerr := q.evaluateNumericAttributeValueNotEqualStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueNotEqualStmt: %w", cerr)
		}
	}
	if q.evaluateNumericAttributeValueNotInclusionStmt != nil {
		if cerr := q.evaluateNumericAttributeValueNotInclusionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateNumericAttributeValueNotInclusionStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueEqualStmt != nil {
		if cerr := q.evaluateStringAttributeValueEqualStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueEqualStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueGlobStmt != nil {
		if cerr := q.evaluateStringAttributeValueGlobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueGlobStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueGreaterOrEqualThanStmt != nil {
		if cerr := q.evaluateStringAttributeValueGreaterOrEqualThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueGreaterOrEqualThanStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueGreaterThanStmt != nil {
		if cerr := q.evaluateStringAttributeValueGreaterThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueGreaterThanStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueInclusionStmt != nil {
		if cerr := q.evaluateStringAttributeValueInclusionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueInclusionStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueLessOrEqualThanStmt != nil {
		if cerr := q.evaluateStringAttributeValueLessOrEqualThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueLessOrEqualThanStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueLowerThanStmt != nil {
		if cerr := q.evaluateStringAttributeValueLowerThanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueLowerThanStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueNotEqualStmt != nil {
		if cerr := q.evaluateStringAttributeValueNotEqualStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueNotEqualStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueNotGlobStmt != nil {
		if cerr := q.evaluateStringAttributeValueNotGlobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueNotGlobStmt: %w", cerr)
		}
	}
	if q.evaluateStringAttributeValueNotInclusionStmt != nil {
		if cerr := q.evaluateStringAttributeValueNotInclusionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing evaluateStringAttributeValueNotInclusionStmt: %w", cerr)
		}
	}
	if q.getLastBlockStmt != nil {
		if cerr := q.getLastBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastBlockStmt: %w", cerr)
		}
	}
	if q.getNumberOfEntitiesStmt != nil {
		if cerr := q.getNumberOfEntitiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNumberOfEntitiesStmt: %w", cerr)
		}
	}
	if q.getNumericAttributeValueBitmapStmt != nil {
		if cerr := q.getNumericAttributeValueBitmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNumericAttributeValueBitmapStmt: %w", cerr)
		}
	}
	if q.getPayloadForEntityKeyStmt != nil {
		if cerr := q.getPayloadForEntityKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPayloadForEntityKeyStmt: %w", cerr)
		}
	}
	if q.getStringAttributeValueBitmapStmt != nil {
		if cerr := q.getStringAttributeValueBitmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStringAttributeValueBitmapStmt: %w", cerr)
		}
	}
	if q.retrievePayloadsStmt != nil {
		if cerr := q.retrievePayloadsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing retrievePayloadsStmt: %w", cerr)
		}
	}
	if q.upsertLastBlockStmt != nil {
		if cerr := q.upsertLastBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertLastBlockStmt: %w", cerr)
		}
	}
	if q.upsertNumericAttributeValueBitmapStmt != nil {
		if cerr := q.upsertNumericAttributeValueBitmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertNumericAttributeValueBitmapStmt: %w", cerr)
		}
	}
	if q.upsertPayloadStmt != nil {
		if cerr := q.upsertPayloadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertPayloadStmt: %w", cerr)
		}
	}
	if q.upsertStringAttributeValueBitmapStmt != nil {
		if cerr := q.upsertStringAttributeValueBitmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertStringAttributeValueBitmapStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                                  DBTX
	tx                                                  *sql.Tx
	deleteNumericAttributeValueBitmapStmt               *sql.Stmt
	deletePayloadForEntityKeyStmt                       *sql.Stmt
	deleteStringAttributeValueBitmapStmt                *sql.Stmt
	evaluateAllStmt                                     *sql.Stmt
	evaluateNumericAttributeValueEqualStmt              *sql.Stmt
	evaluateNumericAttributeValueGreaterOrEqualThanStmt *sql.Stmt
	evaluateNumericAttributeValueGreaterThanStmt        *sql.Stmt
	evaluateNumericAttributeValueInclusionStmt          *sql.Stmt
	evaluateNumericAttributeValueLessOrEqualThanStmt    *sql.Stmt
	evaluateNumericAttributeValueLowerThanStmt          *sql.Stmt
	evaluateNumericAttributeValueNotEqualStmt           *sql.Stmt
	evaluateNumericAttributeValueNotInclusionStmt       *sql.Stmt
	evaluateStringAttributeValueEqualStmt               *sql.Stmt
	evaluateStringAttributeValueGlobStmt                *sql.Stmt
	evaluateStringAttributeValueGreaterOrEqualThanStmt  *sql.Stmt
	evaluateStringAttributeValueGreaterThanStmt         *sql.Stmt
	evaluateStringAttributeValueInclusionStmt           *sql.Stmt
	evaluateStringAttributeValueLessOrEqualThanStmt     *sql.Stmt
	evaluateStringAttributeValueLowerThanStmt           *sql.Stmt
	evaluateStringAttributeValueNotEqualStmt            *sql.Stmt
	evaluateStringAttributeValueNotGlobStmt             *sql.Stmt
	evaluateStringAttributeValueNotInclusionStmt        *sql.Stmt
	getLastBlockStmt                                    *sql.Stmt
	getNumberOfEntitiesStmt                             *sql.Stmt
	getNumericAttributeValueBitmapStmt                  *sql.Stmt
	getPayloadForEntityKeyStmt                          *sql.Stmt
	getStringAttributeValueBitmapStmt                   *sql.Stmt
	retrievePayloadsStmt                                *sql.Stmt
	upsertLastBlockStmt                                 *sql.Stmt
	upsertNumericAttributeValueBitmapStmt               *sql.Stmt
	upsertPayloadStmt                                   *sql.Stmt
	upsertStringAttributeValueBitmapStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		deleteNumericAttributeValueBitmapStmt:  q.deleteNumericAttributeValueBitmapStmt,
		deletePayloadForEntityKeyStmt:          q.deletePayloadForEntityKeyStmt,
		deleteStringAttributeValueBitmapStmt:   q.deleteStringAttributeValueBitmapStmt,
		evaluateAllStmt:                        q.evaluateAllStmt,
		evaluateNumericAttributeValueEqualStmt: q.evaluateNumericAttributeValueEqualStmt,
		evaluateNumericAttributeValueGreaterOrEqualThanStmt: q.evaluateNumericAttributeValueGreaterOrEqualThanStmt,
		evaluateNumericAttributeValueGreaterThanStmt:        q.evaluateNumericAttributeValueGreaterThanStmt,
		evaluateNumericAttributeValueInclusionStmt:          q.evaluateNumericAttributeValueInclusionStmt,
		evaluateNumericAttributeValueLessOrEqualThanStmt:    q.evaluateNumericAttributeValueLessOrEqualThanStmt,
		evaluateNumericAttributeValueLowerThanStmt:          q.evaluateNumericAttributeValueLowerThanStmt,
		evaluateNumericAttributeValueNotEqualStmt:           q.evaluateNumericAttributeValueNotEqualStmt,
		evaluateNumericAttributeValueNotInclusionStmt:       q.evaluateNumericAttributeValueNotInclusionStmt,
		evaluateStringAttributeValueEqualStmt:               q.evaluateStringAttributeValueEqualStmt,
		evaluateStringAttributeValueGlobStmt:                q.evaluateStringAttributeValueGlobStmt,
		evaluateStringAttributeValueGreaterOrEqualThanStmt:  q.evaluateStringAttributeValueGreaterOrEqualThanStmt,
		evaluateStringAttributeValueGreaterThanStmt:         q.evaluateStringAttributeValueGreaterThanStmt,
		evaluateStringAttributeValueInclusionStmt:           q.evaluateStringAttributeValueInclusionStmt,
		evaluateStringAttributeValueLessOrEqualThanStmt:     q.evaluateStringAttributeValueLessOrEqualThanStmt,
		evaluateStringAttributeValueLowerThanStmt:           q.evaluateStringAttributeValueLowerThanStmt,
		evaluateStringAttributeValueNotEqualStmt:            q.evaluateStringAttributeValueNotEqualStmt,
		evaluateStringAttributeValueNotGlobStmt:             q.evaluateStringAttributeValueNotGlobStmt,
		evaluateStringAttributeValueNotInclusionStmt:        q.evaluateStringAttributeValueNotInclusionStmt,
		getLastBlockStmt:                      q.getLastBlockStmt,
		getNumberOfEntitiesStmt:               q.getNumberOfEntitiesStmt,
		getNumericAttributeValueBitmapStmt:    q.getNumericAttributeValueBitmapStmt,
		getPayloadForEntityKeyStmt:            q.getPayloadForEntityKeyStmt,
		getStringAttributeValueBitmapStmt:     q.getStringAttributeValueBitmapStmt,
		retrievePayloadsStmt:                  q.retrievePayloadsStmt,
		upsertLastBlockStmt:                   q.upsertLastBlockStmt,
		upsertNumericAttributeValueBitmapStmt: q.upsertNumericAttributeValueBitmapStmt,
		upsertPayloadStmt:                     q.upsertPayloadStmt,
		upsertStringAttributeValueBitmapStmt:  q.upsertStringAttributeValueBitmapStmt,
	}
}
