// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type LastBlock struct {
	ID    int64
	Block int64
}

type NumericAttributesValuesBitmap struct {
	Name   string
	Value  uint64
	Bitmap *Bitmap
}

type Payload struct {
	ID                uint64
	EntityKey         []byte
	Payload           []byte
	ContentType       string
	StringAttributes  StringAttributes
	NumericAttributes NumericAttributes
}

type StringAttributesValuesBitmap struct {
	Name   string
	Value  string
	Bitmap *Bitmap
}
