// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type LastBlock struct {
	ID    int64
	Block int64
}

type NumericAttributesValuesBitmap struct {
	Name   string
	Value  uint64
	Bitmap []byte
}

type Payload struct {
	EntityKey         []byte
	ID                uint64
	Payload           []byte
	ContentType       string
	StringAttributes  string
	NumericAttributes string
}

type StringAttributesValuesBitmap struct {
	Name   string
	Value  string
	Bitmap []byte
}
