// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type AttributesValuesBitmap struct {
	Name   string
	Value  string
	Type   string
	Bitmap []byte
}

type LastBlock struct {
	ID    int64
	Block int64
}

type Payload struct {
	ID                int64
	Payload           []byte
	ContentType       string
	StringAttributes  string
	NumericAttributes string
}
