// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const getAttributeValueBitmap = `-- name: GetAttributeValueBitmap :one
SELECT bitmap FROM ATTRIBUTES_VALUES_BITMAPS
WHERE name = ? AND value = ? AND type = ?
`

type GetAttributeValueBitmapParams struct {
	Name  string
	Value string
	Type  string
}

func (q *Queries) GetAttributeValueBitmap(ctx context.Context, arg GetAttributeValueBitmapParams) ([]byte, error) {
	row := q.queryRow(ctx, q.getAttributeValueBitmapStmt, getAttributeValueBitmap, arg.Name, arg.Value, arg.Type)
	var bitmap []byte
	err := row.Scan(&bitmap)
	return bitmap, err
}

const insertPayload = `-- name: InsertPayload :exec
INSERT INTO payloads (
    id,
    payload,
    content_type,
    string_attributes,
    numeric_attributes
) VALUES (?, ?, ?, ?, ?)
`

type InsertPayloadParams struct {
	ID                int64
	Payload           []byte
	ContentType       string
	StringAttributes  string
	NumericAttributes string
}

func (q *Queries) InsertPayload(ctx context.Context, arg InsertPayloadParams) error {
	_, err := q.exec(ctx, q.insertPayloadStmt, insertPayload,
		arg.ID,
		arg.Payload,
		arg.ContentType,
		arg.StringAttributes,
		arg.NumericAttributes,
	)
	return err
}

const upsertAttributeValueBitmap = `-- name: UpsertAttributeValueBitmap :exec
INSERT INTO ATTRIBUTES_VALUES_BITMAPS (name, value, type, bitmap)
VALUES (?, ?, ?, ?)
ON CONFLICT (name, value, type) DO UPDATE SET bitmap = excluded.bitmap
`

type UpsertAttributeValueBitmapParams struct {
	Name   string
	Value  string
	Type   string
	Bitmap []byte
}

func (q *Queries) UpsertAttributeValueBitmap(ctx context.Context, arg UpsertAttributeValueBitmapParams) error {
	_, err := q.exec(ctx, q.upsertAttributeValueBitmapStmt, upsertAttributeValueBitmap,
		arg.Name,
		arg.Value,
		arg.Type,
		arg.Bitmap,
	)
	return err
}
