// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	GetAttributeValueBitmap(ctx context.Context, arg GetAttributeValueBitmapParams) ([]byte, error)
	InsertPayload(ctx context.Context, arg InsertPayloadParams) error
	UpsertAttributeValueBitmap(ctx context.Context, arg UpsertAttributeValueBitmapParams) error
}

var _ Querier = (*Queries)(nil)
