// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const deleteNumericAttributeValueBitmap = `-- name: DeleteNumericAttributeValueBitmap :exec
DELETE FROM numeric_attributes_values_bitmaps
WHERE
    name = ?
    AND value = ?
`

type DeleteNumericAttributeValueBitmapParams struct {
	Name  string
	Value uint64
}

func (q *Queries) DeleteNumericAttributeValueBitmap(ctx context.Context, arg DeleteNumericAttributeValueBitmapParams) error {
	_, err := q.exec(ctx, q.deleteNumericAttributeValueBitmapStmt, deleteNumericAttributeValueBitmap, arg.Name, arg.Value)
	return err
}

const deletePayloadForEntityKey = `-- name: DeletePayloadForEntityKey :exec
DELETE FROM payloads WHERE entity_key = ?
`

func (q *Queries) DeletePayloadForEntityKey(ctx context.Context, entityKey []byte) error {
	_, err := q.exec(ctx, q.deletePayloadForEntityKeyStmt, deletePayloadForEntityKey, entityKey)
	return err
}

const deleteStringAttributeValueBitmap = `-- name: DeleteStringAttributeValueBitmap :exec
DELETE FROM string_attributes_values_bitmaps
WHERE
    name = ?
    AND value = ?
`

type DeleteStringAttributeValueBitmapParams struct {
	Name  string
	Value string
}

func (q *Queries) DeleteStringAttributeValueBitmap(ctx context.Context, arg DeleteStringAttributeValueBitmapParams) error {
	_, err := q.exec(ctx, q.deleteStringAttributeValueBitmapStmt, deleteStringAttributeValueBitmap, arg.Name, arg.Value)
	return err
}

const doltAdd = `-- name: DoltAdd :exec
CALL DOLT_ADD ('.')
`

func (q *Queries) DoltAdd(ctx context.Context) error {
	_, err := q.exec(ctx, q.doltAddStmt, doltAdd)
	return err
}

const doltCommit = `-- name: DoltCommit :exec
CALL DOLT_COMMIT ('-m', ?)
`

func (q *Queries) DoltCommit(ctx context.Context, message interface{}) error {
	_, err := q.exec(ctx, q.doltCommitStmt, doltCommit, message)
	return err
}

const getLastBlock = `-- name: GetLastBlock :one
SELECT block FROM last_block
`

func (q *Queries) GetLastBlock(ctx context.Context) (uint64, error) {
	row := q.queryRow(ctx, q.getLastBlockStmt, getLastBlock)
	var block uint64
	err := row.Scan(&block)
	return block, err
}

const getNumericAttributeValueBitmap = `-- name: GetNumericAttributeValueBitmap :one
SELECT bitmap
FROM
    numeric_attributes_values_bitmaps
WHERE
    name = ?
    AND value = ?
`

type GetNumericAttributeValueBitmapParams struct {
	Name  string
	Value uint64
}

func (q *Queries) GetNumericAttributeValueBitmap(ctx context.Context, arg GetNumericAttributeValueBitmapParams) (*Bitmap, error) {
	row := q.queryRow(ctx, q.getNumericAttributeValueBitmapStmt, getNumericAttributeValueBitmap, arg.Name, arg.Value)
	var bitmap *Bitmap
	err := row.Scan(&bitmap)
	return bitmap, err
}

const getPayloadForEntityKey = `-- name: GetPayloadForEntityKey :one
SELECT
    entity_key,
    id,
    payload,
    content_type,
    string_attributes,
    numeric_attributes
FROM payloads
WHERE
    entity_key = ?
`

type GetPayloadForEntityKeyRow struct {
	EntityKey         []byte
	ID                uint64
	Payload           []byte
	ContentType       string
	StringAttributes  *StringAttributes
	NumericAttributes *NumericAttributes
}

func (q *Queries) GetPayloadForEntityKey(ctx context.Context, entityKey []byte) (GetPayloadForEntityKeyRow, error) {
	row := q.queryRow(ctx, q.getPayloadForEntityKeyStmt, getPayloadForEntityKey, entityKey)
	var i GetPayloadForEntityKeyRow
	err := row.Scan(
		&i.EntityKey,
		&i.ID,
		&i.Payload,
		&i.ContentType,
		&i.StringAttributes,
		&i.NumericAttributes,
	)
	return i, err
}

const getStringAttributeValueBitmap = `-- name: GetStringAttributeValueBitmap :one
SELECT bitmap
FROM
    string_attributes_values_bitmaps
WHERE
    name = ?
    AND value = ?
`

type GetStringAttributeValueBitmapParams struct {
	Name  string
	Value string
}

func (q *Queries) GetStringAttributeValueBitmap(ctx context.Context, arg GetStringAttributeValueBitmapParams) (*Bitmap, error) {
	row := q.queryRow(ctx, q.getStringAttributeValueBitmapStmt, getStringAttributeValueBitmap, arg.Name, arg.Value)
	var bitmap *Bitmap
	err := row.Scan(&bitmap)
	return bitmap, err
}

const upsertLastBlock = `-- name: UpsertLastBlock :exec
INSERT INTO
    last_block (id, block)
VALUES (1, ?)
ON DUPLICATE KEY UPDATE
    block = VALUES(block)
`

func (q *Queries) UpsertLastBlock(ctx context.Context, block uint64) error {
	_, err := q.exec(ctx, q.upsertLastBlockStmt, upsertLastBlock, block)
	return err
}

const upsertNumericAttributeValueBitmap = `-- name: UpsertNumericAttributeValueBitmap :exec
INSERT INTO
    numeric_attributes_values_bitmaps (name, value, bitmap)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE
    bitmap = VALUES(bitmap)
`

type UpsertNumericAttributeValueBitmapParams struct {
	Name   string
	Value  uint64
	Bitmap *Bitmap
}

func (q *Queries) UpsertNumericAttributeValueBitmap(ctx context.Context, arg UpsertNumericAttributeValueBitmapParams) error {
	_, err := q.exec(ctx, q.upsertNumericAttributeValueBitmapStmt, upsertNumericAttributeValueBitmap, arg.Name, arg.Value, arg.Bitmap)
	return err
}

const upsertPayload = `-- name: UpsertPayload :execresult
INSERT INTO
    payloads (
        entity_key,
        payload,
        content_type,
        string_attributes,
        numeric_attributes
    )
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    id = LAST_INSERT_ID(id),
    payload = VALUES(payload),
    content_type = VALUES(content_type),
    string_attributes = VALUES(string_attributes),
    numeric_attributes = VALUES(numeric_attributes)
`

type UpsertPayloadParams struct {
	EntityKey         []byte
	Payload           []byte
	ContentType       string
	StringAttributes  *StringAttributes
	NumericAttributes *NumericAttributes
}

func (q *Queries) UpsertPayload(ctx context.Context, arg UpsertPayloadParams) (sql.Result, error) {
	return q.exec(ctx, q.upsertPayloadStmt, upsertPayload,
		arg.EntityKey,
		arg.Payload,
		arg.ContentType,
		arg.StringAttributes,
		arg.NumericAttributes,
	)
}

const upsertStringAttributeValueBitmap = `-- name: UpsertStringAttributeValueBitmap :exec
INSERT INTO
    string_attributes_values_bitmaps (name, value, bitmap)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE
    bitmap = VALUES(bitmap)
`

type UpsertStringAttributeValueBitmapParams struct {
	Name   string
	Value  string
	Bitmap *Bitmap
}

func (q *Queries) UpsertStringAttributeValueBitmap(ctx context.Context, arg UpsertStringAttributeValueBitmapParams) error {
	_, err := q.exec(ctx, q.upsertStringAttributeValueBitmapStmt, upsertStringAttributeValueBitmap, arg.Name, arg.Value, arg.Bitmap)
	return err
}
