// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retrieve.sql

package store

import (
	"context"
	"strings"
)

const retrievePayloads = `-- name: RetrievePayloads :many
SELECT entity_key, id, payload, content_type, string_attributes, numeric_attributes
FROM payloads
WHERE id IN (/*SLICE:ids*/?)
`

type RetrievePayloadsRow struct {
	EntityKey         []byte
	ID                uint64
	Payload           []byte
	ContentType       string
	StringAttributes  *StringAttributes
	NumericAttributes *NumericAttributes
}

func (q *Queries) RetrievePayloads(ctx context.Context, ids []uint64) ([]RetrievePayloadsRow, error) {
	query := retrievePayloads
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetrievePayloadsRow{}
	for rows.Next() {
		var i RetrievePayloadsRow
		if err := rows.Scan(
			&i.EntityKey,
			&i.ID,
			&i.Payload,
			&i.ContentType,
			&i.StringAttributes,
			&i.NumericAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
